
import { QuizQuestion, QuizDifficulty } from './types';

export const PROGRAM_DIRECTOR = "Innocent Forteh";

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    question: "What is a 'prompt' in the context of Large Language Models (LLMs)?",
    options: [
      "A software bug",
      "The input text given to the model to guide its output",
      "The final output generated by the AI",
      "A type of computer hardware"
    ],
    correctAnswer: "The input text given to the model to guide its output",
    difficulty: QuizDifficulty.EASY,
  },
  {
    question: "What is 'zero-shot' prompting?",
    options: [
      "Asking the model a question without providing any examples",
      "A prompt that always results in an error",
      "Providing multiple examples in the prompt",
      "A prompt that is empty"
    ],
    correctAnswer: "Asking the model a question without providing any examples",
    difficulty: QuizDifficulty.MEDIUM,
  },
  {
    question: "Which of the following is a good practice for writing effective prompts?",
    options: [
      "Being as vague as possible",
      "Using complex and ambiguous language",
      "Providing clear, specific instructions and context",
      "Writing the entire prompt in capital letters"
    ],
    correctAnswer: "Providing clear, specific instructions and context",
    difficulty: QuizDifficulty.EASY,
  },
  {
    question: "What does the term 'Hallucination' mean when discussing AI models?",
    options: [
      "The AI generates creative and artistic content",
      "The AI processes images and visual data",
      "The AI confidently provides incorrect or nonsensical information",
      "The AI can understand human emotions"
    ],
    correctAnswer: "The AI confidently provides incorrect or nonsensical information",
    difficulty: QuizDifficulty.HARD,
  },
  {
    question: "Assigning a specific role to an AI in a prompt, like 'Act as a travel guide', is an example of what technique?",
    options: [
      "Chain-of-thought prompting",
      "Zero-shot prompting",
      "Persona pattern",
      "Model fine-tuning"
    ],
    correctAnswer: "Persona pattern",
    difficulty: QuizDifficulty.MEDIUM,
  },
];